import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "..");
const packagePath = path.join(repositoryRoot, "tsbot", "package.json");
const lockPath = path.join(repositoryRoot, "tsbot", "package-lock.json");
const generatedPath = path.join(
  repositoryRoot,
  "tsbot",
  "src",
  "generated-version.ts",
);
const readmePath = path.join(repositoryRoot, "README.md");
const portableReadmePath = path.join(
  repositoryRoot,
  "windows",
  "PORTABLE-README.txt",
);
const semverPattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;
const documentationVersions = [
  {
    fileName: readmePath,
    label: "README current release",
    pattern: /^Superior (\d+\.\d+\.\d+) is /mu,
    replacement: (version) => `Superior ${version} is `,
  },
  {
    fileName: portableReadmePath,
    label: "portable README current release",
    pattern: /^Version (\d+\.\d+\.\d+) will not start/mu,
    replacement: (version) => `Version ${version} will not start`,
  },
];

function readJson(fileName) {
  return JSON.parse(fs.readFileSync(fileName, "utf8"));
}

function writeJson(fileName, value) {
  fs.writeFileSync(fileName, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function generatedSource(version) {
  return [
    "/** Generated from tsbot/package.json by scripts/version.mjs. */",
    "// Do not edit this file by hand.",
    `export const PACKAGE_VERSION = ${JSON.stringify(version)};`,
    "",
  ].join("\n");
}

function updateDocumentationVersions(version) {
  for (const definition of documentationVersions) {
    const original = fs.readFileSync(definition.fileName, "utf8");
    if (!definition.pattern.test(original)) {
      throw new Error(`Could not locate ${definition.label} marker.`);
    }
    const updated = original.replace(
      definition.pattern,
      definition.replacement(version),
    );
    fs.writeFileSync(definition.fileName, updated, "utf8");
  }
}

function readPackageIdentity() {
  const packageJson = readJson(packagePath);
  if (packageJson.name !== "superior-discord-bot") {
    throw new Error(`Unexpected package name: ${String(packageJson.name)}`);
  }
  if (!semverPattern.test(String(packageJson.version))) {
    throw new Error(
      `tsbot/package.json version must be MAJOR.MINOR.PATCH: ${String(packageJson.version)}`,
    );
  }
  if (
    String(packageJson.version)
      .split(".")
      .some((part) => Number(part) > 65_534)
  ) {
    throw new Error(
      `Package version exceeds the Windows assembly metadata limit: ${String(packageJson.version)}`,
    );
  }
  return packageJson;
}

function verify() {
  const packageJson = readPackageIdentity();
  const lockJson = readJson(lockPath);
  const lockRoot = lockJson.packages?.[""];
  const mismatches = [];

  if (
    lockJson.name !== packageJson.name ||
    lockRoot?.name !== packageJson.name
  ) {
    mismatches.push("package-lock package name");
  }
  if (
    lockJson.version !== packageJson.version ||
    lockRoot?.version !== packageJson.version
  ) {
    mismatches.push("package-lock version");
  }

  const expectedGenerated = generatedSource(packageJson.version);
  const actualGenerated = fs.existsSync(generatedPath)
    ? fs.readFileSync(generatedPath, "utf8").replaceAll("\r\n", "\n")
    : "";
  if (actualGenerated !== expectedGenerated) {
    mismatches.push("generated runtime version");
  }
  for (const definition of documentationVersions) {
    const match = definition.pattern.exec(
      fs.readFileSync(definition.fileName, "utf8"),
    );
    if (match?.[1] !== packageJson.version) {
      mismatches.push(definition.label);
    }
  }

  if (mismatches.length > 0) {
    throw new Error(
      `Version metadata is out of sync (${mismatches.join(", ")}). Run npm run version:generate.`,
    );
  }

  console.log(`[version] verified ${packageJson.version}`);
}

function generate() {
  const packageJson = readPackageIdentity();
  const lockJson = readJson(lockPath);
  const lockRoot = lockJson.packages?.[""];
  if (!lockRoot || typeof lockRoot !== "object") {
    throw new Error("package-lock.json is missing its root package record.");
  }
  if (
    lockJson.name !== packageJson.name ||
    lockRoot.name !== packageJson.name
  ) {
    throw new Error(
      "package-lock.json names a different package. Repair the lockfile before generating a version.",
    );
  }
  const originals = new Map(
    [lockPath, generatedPath, readmePath, portableReadmePath].map(
      (fileName) => [fileName, fs.readFileSync(fileName)],
    ),
  );
  try {
    if (
      lockJson.version !== packageJson.version ||
      lockRoot.version !== packageJson.version
    ) {
      lockJson.version = packageJson.version;
      lockRoot.version = packageJson.version;
      writeJson(lockPath, lockJson);
    }
    fs.writeFileSync(
      generatedPath,
      generatedSource(packageJson.version),
      "utf8",
    );
    updateDocumentationVersions(packageJson.version);
  } catch (error) {
    for (const [fileName, contents] of originals) {
      fs.writeFileSync(fileName, contents);
    }
    throw error;
  }
  console.log(`[version] generated runtime identity ${packageJson.version}`);
}

function nextVersion(current, level) {
  const match = semverPattern.exec(current);
  if (!match) {
    throw new Error(`Invalid current semantic version: ${current}`);
  }
  let major = Number(match[1]);
  let minor = Number(match[2]);
  let patch = Number(match[3]);
  switch (level) {
    case "major":
      major += 1;
      minor = 0;
      patch = 0;
      break;
    case "minor":
      minor += 1;
      patch = 0;
      break;
    case "patch":
      patch += 1;
      break;
    default:
      throw new Error("Version level must be patch, minor, or major.");
  }
  return `${major}.${minor}.${patch}`;
}

function bump(level) {
  const packageJson = readPackageIdentity();
  const lockJson = readJson(lockPath);
  const lockRoot = lockJson.packages?.[""];
  if (!lockRoot || typeof lockRoot !== "object") {
    throw new Error("package-lock.json is missing its root package record.");
  }
  if (
    lockJson.name !== packageJson.name ||
    lockRoot.name !== packageJson.name ||
    lockJson.version !== packageJson.version ||
    lockRoot.version !== packageJson.version
  ) {
    throw new Error(
      "Refusing to bump inconsistent package metadata. Run npm run version:verify and repair the reported mismatch first.",
    );
  }

  const previous = packageJson.version;
  const version = nextVersion(previous, level);
  if (version.split(".").some((part) => Number(part) > 65_534)) {
    throw new Error(
      `The requested version exceeds the Windows assembly metadata limit: ${version}`,
    );
  }
  packageJson.version = version;
  lockJson.version = version;
  lockRoot.version = version;
  const originals = new Map(
    [packagePath, lockPath, generatedPath, readmePath, portableReadmePath].map(
      (fileName) => [fileName, fs.readFileSync(fileName)],
    ),
  );
  try {
    writeJson(packagePath, packageJson);
    writeJson(lockPath, lockJson);
    fs.writeFileSync(generatedPath, generatedSource(version), "utf8");
    updateDocumentationVersions(version);
  } catch (error) {
    for (const [fileName, contents] of originals) {
      fs.writeFileSync(fileName, contents);
    }
    throw error;
  }
  console.log(`[version] bumped ${previous} -> ${version} (${level})`);
}

const [command = "verify", argument] = process.argv.slice(2);
try {
  switch (command) {
    case "verify":
      verify();
      break;
    case "generate":
      generate();
      verify();
      break;
    case "bump":
      bump(argument);
      verify();
      break;
    default:
      throw new Error(
        "Usage: version.mjs verify | generate | bump <patch|minor|major>",
      );
  }
} catch (error) {
  console.error(
    `[version:error] ${error instanceof Error ? error.message : String(error)}`,
  );
  process.exitCode = 1;
}
